#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

gunicorn --workers=2 --worker-class=gevent --worker-connections=1000 kapoorsoftwaresolutions.wsgi --bind 0.0.0.0:8000