#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

worker_ready() {
    celery -A kapoorsoftwaresolutions inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A kapoorsoftwaresolutions --broker="${REDIS_URL}" flower --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"